/*
 * Practice 2: Calling a Macro from a TITLE Statement
 * Lesson 4 - Creating and Using Macro Programs
 * SAS Macro Language 1: Essentials
 */
/* Task:
In this practice, you define a macro program named Currtime that displays the current time.  Then you print selected observations from the SAS data set orion.customer_dim and reference the Currtime macro in the title for this report.

Reminder: Make sure you've defined the Orion library.
1. Define a macro that calls the SAS function, TIME, and displays it in the TIMEAMPM. format. Name the macro Currtime. Submit the macro definition.


2. Copy and paste the following code into the editor.
title 'Customer List';
proc print data=orion.customer_dim(obs=10);
   var Customer_Name Customer_Group;
run;
title;

3. Add a TITLE2 statement. Call the macro Currtime from the TITLE2 statement. Submit the program and examine the results.

4. Enable the MPRINT option, resubmit the code, and view the results. Are any messages generated by MPRINT? Why or why not?
*/

/* 1.*/
%macro Currtime;
	%sysfunc(time(), TIMEAMPM.)
%mend;


/* 2. , 3. , 4.*/
options mprint;

title 'Customer List';
title2 "%currtime"; /*use "..."*/
proc print data=orion.customer_dim(obs=10);
   var Customer_Name Customer_Group;
run;
title;

/*Although you enabled the MPRINT option, SAS does not display 
any MPRINT messages in the log. 
This is because the Currtime macro does not generate any SAS code. 

It simply calls %SYSFUNC to invoke the TIME function. 
SAS formats the returned value, places it on the input stack 
and uses it in the TITLE statement. 
SAS does not display the function or the returned value in the log.*/